export const mockData = [
    {
        id: 1,
        batchId: 1,
        batchName: 'Công đoạn 1',
        startTime: '2026-02-03 10:32:44',
        status: 2,
        videoRecorded: true,
        estimatedTime: 30,
        chemicals: [
            {
                code: '07.00.0043',
                numberOrder: 'CH-01',
                name: 'H2SO4',
                quantity: '15.5',
                unit: 'kg',
                concentration: '100',
                state: 'liquid',
                temperature: '45',
                scanned: true,
            },
            {
                code: '06.01.0043',
                numberOrder: 'CH-02',
                name: 'NaOH',
                quantity: '10',
                unit: 'kg',
                concentration: '9.6',
                state: 'solid',
                temperature: '25',
                scanned: true,
            },
            {
                code: '06.02.0043',
                numberOrder: 'CH-03',
                name: 'HCl',
                quantity: '2.5',
                unit: 'kg',
                concentration: '3.7',
                state: 'liquid',
                temperature: '20',
                scanned: false,
            },
            {
                code: '06.03.0043',
                numberOrder: 'CH-04',
                name: 'Distilled water',
                quantity: '100',
                unit: 'L',
                concentration: '0.6',
                state: 'liquid',
                temperature: '25',
                scanned: false,
            },
        ],
    },
    {
        id: 2,
        batchId: 2,
        batchName: 'Công đoạn 2',
        startTime: '',
        status: 2,
        estimatedTime: 100,
        videoRecorded: false,
        chemicals: [
            {
                code: '06.05.0101',
                numberOrder: '2-0',
                name: 'Lấy mẫu',
                quantity: '80',
                concentration: '-',
                state: 'liquid',
                temperature: '40',
                scanned: false,
            },
            {
                code: '06.05.0101',
                numberOrder: '2-1',
                name: 'NaOH',
                quantity: '250',
                concentration: '95',
                state: 'solid',
                temperature: '25',
                scanned: false,
            },
            {
                code: '06.06.0102',
                numberOrder: '2-2',
                name: 'Ca(OH)₂',
                quantity: '1000',
                concentration: '90',
                state: 'solid',
                temperature: '25',
                scanned: false,
            },
        ],
    },
    {
        id: 3,
        batchId: 3,
        batchName: 'Công đoạn 3',
        startTime: '',
        status: 2,
        estimatedTime: 17,
        videoRecorded: false,
        chemicals: [
            {
                code: '06.05.0101',
                numberOrder: '3-0',
                name: 'Lấy mẫu kiểm tra pH',
                quantity: '50',
                concentration: '-',
                state: 'liquid',
                temperature: '35',
                scanned: false,
            },
            {
                code: '07.01.0201',
                numberOrder: '3-1',
                name: 'H2O',
                quantity: '250',
                concentration: '100',
                state: 'liquid',
                temperature: '30',
                scanned: false,
            },
            {
                code: '07.01.0202',
                numberOrder: '3-2',
                name: 'H2O',
                quantity: '1000',
                concentration: '100',
                state: 'liquid',
                temperature: '30',
                scanned: false,
            },
        ],
    },
];

export const historyOperation = [
    {
        id: 1,
        code: '06.02.0042',
        numberOrder: 'CH-02',
        name: 'NaOH',
        quantity: '10.0',
        unit: 'kg',
        concentration: '100',
        state: 'solid',
        temperature: '25',
        scanned: false,
        time: '14:45',
    },
    {
        id: 2,
        code: '06.03.0043',
        numberOrder: 'CH-01',
        name: 'H2SO4',
        quantity: '15.5',
        unit: 'kg',
        concentration: '0.6',
        state: 'liquid',
        temperature: '25',
        time: '14:30',
        scanned: false,
    },
    {
        time: '14:25',
    }
];

export const orderInfo = {
    id: 1,
    code: 'XJ-00001',
    orderNo: 'PD-2024-001',
    artNo: '474f-UGG.249A',
    name: 'SWAN SUEDE',
    quantity: 120,
    unit: 'kg',
    color: 'Xanh Dương',
    thickness: '5',
    staff: 'Nguyễn Văn A',
    startTime: '14/02/2026 14:30:00',
    endTime: '',
    changedStartTime: '14/02/2026',
    isChangedTime: false,
    status: 'in-progress',
};
