export const mockMachineData = [
    {
        id: 1,
        number: '01',
        name: 'Bồn xoay 1',
        code: '01.01.0001',
        isUsed: true,
        staffName: 'Nguyễn Văn An',
    },
    {
        id: 2,
        number: '02',
        name: 'Bồn xoay 2',
        code: '01.01.0002',
        isUsed: true,
        staffName: 'Nguyễn Văn Bình',
    },
    {
        id: 3,
        number: '03',
        name: 'Bồn xoay 3',
        code: '01.01.0003',
        isUsed: true,
        staffName: 'Nguyễn Văn Cường',
    },
    {
        id: 4,
        number: '04',
        name: 'Bồn xoay 4',
        code: '01.01.0004',
        isUsed: true,
        staffName: 'Nguyễn Văn Đạt',
    },
    {
        id: 5,
        number: '05',
        name: 'Bồn xoay 5',
        code: '01.01.0005',
        isUsed: true,
        staffName: 'Nguyễn Văn Đông',
    },
    {
        id: 6,
        number: '06',
        name: 'Bồn xoay 6',
        code: '01.01.0006',
        isUsed: true,
        staffName: '',
    },
    {
        id: 7,
        number: '07',
        name: 'Bồn xoay 7',
        code: '01.01.0007',
        isUsed: false,
        staffName: '',
    },
    {
        id: 8,
        number: '08',
        name: 'Bồn xoay 8',
        code: '01.01.0008',
        isUsed: false,
        staffName: '',
    },
    {
        id: 9,
        number: '09',
        name: 'Bồn xoay 9',
        code: '01.01.0009',
        isUsed: false,
        staffName: '',
    },
    {
        id: 10,
        number: '10',
        name: 'Bồn xoay 10',
        code: '01.01.0010',
        isUsed: false,
        staffName: '',
    },
    {
        id: 11,
        number: '11',
        name: 'Bồn xoay 11',
        code: '01.01.0011',
        isUsed: false,
        staffName: '',
    },
    {
        id: 12,
        number: 12,
        name: 'Bồn xoay 12',
        code: '01.01.0012',
        isUsed: false,
        staffName: '',
    },
    {
        id: 13,
        number: 13,
        name: 'Bồn xoay 13',
        code: '01.01.0013',
        isUsed: false,
        staffName: '',
    },
    {
        id: 14,
        number: 14,
        name: 'Bồn xoay 14',
        code: '01.01.0014',
        isUsed: false,
        staffName: '',
    },
    {
        id: 15,
        number: 15,
        name: 'Bồn xoay 15',
        code: '01.01.0015',
        isUsed: false,
        staffName: '',
    },
    {
        id: 16,
        number: 16,
        name: 'Bồn xoay 16',
        code: '01.01.0016',
        isUsed: false,
        staffName: '',
    },
    {
        id: 17,
        number: 17,
        name: 'Bồn xoay 17',
        code: '01.01.0017',
        isUsed: false,
        staffName: '',
    },
    {
        id: 18,
        number: 18,
        name: 'Bồn xoay 18',
        code: '01.01.0018',
        isUsed: false,
        staffName: '',
    },
    {
        id: 19,
        number: 19,
        name: 'Bồn xoay 19',
        code: '01.01.0019',
        isUsed: false,
        staffName: '',
    },
    {
        id: 20,
        number: 20,
        name: 'Bồn xoay 20',
        code: '01.01.0020',
        isUsed: false,
        staffName: '',
    },
    {
        id: 21,
        number: 21,
        name: 'Bồn xoay 21',
        code: '01.01.0021',
        isUsed: false,
        staffName: '',
    },
    {
        id: 22,
        number: 22,
        name: 'Bồn xoay 22',
        code: '01.01.0022',
        isUsed: false,
        staffName: '',
    },
    {
        id: 23,
        number: 23,
        name: 'Bồn xoay 23',
        code: '01.01.0023',
        isUsed: false,
        staffName: '',
    },
    {
        id: 24,
        number: 24,
        name: 'Bồn xoay 24',
        code: '01.01.0024',
        isUsed: false,
        staffName: '',
    },
    {
        id: 25,
        number: 25,
        name: 'Bồn xoay 25',
        code: '01.01.0025',
        isUsed: false,
        staffName: '',
    },
];

export const employeeMockData = [
    {
        id: 1,
        name: 'Nguyễn Văn An',
        code: '123456',
    },
    {
        id: 2,
        name: 'Nguyễn Văn Bình',
        code: '123457',
    },
    {
        id: 3,
        name: 'Nguyễn Văn Cường',
        code: '123458',
    },
    {
        id: 4,
        name: 'Nguyễn Văn Đạt',
        code: '123459',
    },
    {
        id: 5,
        name: 'Nguyễn Văn Đông',
        code: '123460',
    },
];
